ZABBIX_URL = "http://seuzabbix/zabbix/api_jsonrpc.php"  #URL ZABBIX SERVER

ZABBIX_TOKEN = "XXXXXXXXXXXXXXXXXXX"   #API TOKEN GERADO NO ZABBIX FRONTEND
 
#LIST DE GRUPOS DE HOSTS. CADA CATEGORIA ENGLOBA TODOS OS HOSTS QUE SERÃO LISTADOS
# NA PLANILHA
HOST_GROUPS =  {  
    "CATEGORIA X": ["GRUPO HOST A","GRUPO HOST B"],
    "CATEGORA B": [""],    
}
# PERÍODO DE HISTÓRICO DO ZABBIX SERVER
START_DATE = "2026-03-09" #Selecionar data inicial
END_DATE = "2026-04-10"   #Selecionar data final

#RELATÓRIO GERADO NA PASTA INDICADA
OUTPUT_FILE = "output/relatorio_disponibilidade_zabbix.xlsx"